[build]
  publish = "."
  command = "echo 'Build complete'"

[build.environment]
  NODE_VERSION = "18"

# PWA 파일들에 대한 캐싱 설정
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/messages.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# HTTPS 리디렉션
[[redirects]]
  from = "http://daily-start-messages.netlify.app/*"
  to = "https://daily-start-messages.netlify.app/:splat"
  status = 301
  force = true

# SPA용 리디렉션 (모든 경로를 index.html로)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 보안 헤더
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self';"

# 개발용 브랜치 설정 (선택사항)
[context.develop]
  command = "echo 'Development build'"

[context.branch-deploy]
  command = "echo 'Branch deploy'"

# Form 처리 (피드백 양식 등에 사용)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true